import { useRef, useState } from "react";
import { CheckCircle2, FileJson, Loader2, ShieldCheck, Upload, XCircle } from "lucide-react";
import { verifyCertificate, type Stage } from "../lib/verify";
import { useReveal } from "../hooks/useReveal";

const SAMPLE_BASE =
  "https://raw.githubusercontent.com/lobinni/pactmark/main/examples/demo-agreement";

type RunState = "idle" | "running" | "done";

export function Verify() {
  const [certificateText, setCertificateText] = useState("");
  const [bundleText, setBundleText] = useState("");
  const [parseError, setParseError] = useState("");
  const [notice, setNotice] = useState("");
  const [stages, setStages] = useState<Stage[] | null>(null);
  const [runState, setRunState] = useState<RunState>("idle");
  const certFileRef = useRef<HTMLInputElement>(null);
  const bundleFileRef = useRef<HTMLInputElement>(null);

  useReveal(stages);

  const passed = stages?.every((stage) => stage.checks.every((check) => check.pass)) ?? false;
  const totalChecks = stages?.reduce((sum, stage) => sum + stage.checks.length, 0) ?? 0;
  const failedChecks =
    stages?.reduce((sum, stage) => sum + stage.checks.filter((check) => !check.pass).length, 0) ?? 0;

  function readFile(file: File, target: "certificate" | "bundle") {
    const reader = new FileReader();
    reader.onload = () => {
      const text = String(reader.result ?? "");
      if (target === "certificate") setCertificateText(text);
      else setBundleText(text);
      setNotice(`${file.name} loaded.`);
    };
    reader.readAsText(file);
  }

  async function run(certSource: string, bundleSource: string) {
    setRunState("running");
    setParseError("");
    setStages(null);
    try {
      const cert = JSON.parse(certSource);
      const bundle = bundleSource.trim() ? JSON.parse(bundleSource) : undefined;
      const result = await verifyCertificate(cert, bundle);
      setStages(result);
      setRunState("done");
    } catch (error) {
      setParseError(error instanceof Error ? error.message : String(error));
      setRunState("idle");
    }
  }

  async function loadSample() {
    setNotice("Fetching the settled sample from the repository…");
    setParseError("");
    try {
      const [certResponse, bundleResponse] = await Promise.all([
        fetch(`${SAMPLE_BASE}/certificate-settled.json`),
        fetch(`${SAMPLE_BASE}/bundle-settled.json`),
      ]);
      if (!certResponse.ok || !bundleResponse.ok) throw new Error("sample not published yet");
      const cert = await certResponse.text();
      const bundle = await bundleResponse.text();
      setCertificateText(cert);
      setBundleText(bundle);
      setNotice("Sample loaded — verifying it now.");
      await run(cert, bundle);
    } catch {
      setNotice(
        "The sample files are generated by scripts/demo/run_demo.py and were not reachable. Paste a certificate or drop a file instead."
      );
    }
  }

  return (
    <section id="verify" className="py-24 sm:py-32 bg-paper-2/60">
      <div className="wrap grid lg:grid-cols-[0.9fr_1.1fr] gap-14">
        <div>
          <p className="kicker" data-reveal>
            Independent verification
          </p>
          <h2 className="display text-4xl sm:text-[52px] mt-7" data-reveal="1">
            Trust the bytes, not the banner.
          </h2>
          <p className="lede mt-6" data-reveal="2">
            A sealed Pactmark certificate proves itself. This page recomputes the canonical hash,
            every evidence hash and every quoted passage inside your browser — the same algorithm
            as the offline verifier in the repository. Nothing is uploaded anywhere.
          </p>
          <ol className="mt-9 space-y-5" data-reveal="3">
            {[
              "Get the certificate JSON — download it from the live console above or read get_certificate from the contract.",
              "Drop it on the right. Optionally add the evidence bundle for quote grounding.",
              "Compare the recomputed hash with get_certificate_hash on-chain. If a single byte was touched, the hashes diverge.",
            ].map((text, index) => (
              <li key={text} className="flex gap-4">
                <span className="step-no shrink-0 pt-0.5">{String(index + 1).padStart(2, "0")}</span>
                <p className="text-[13.5px] leading-[1.8] text-ink-2">{text}</p>
              </li>
            ))}
          </ol>
          <button onClick={() => void loadSample()} className="btn-line mt-10" data-reveal="3">
            {runState === "running" ? <Loader2 size={16} className="animate-spin" /> : <ShieldCheck size={16} />}
            Try the settled sample
          </button>
        </div>

        <div className="card p-8" data-reveal="2">
          <div className="flex items-center justify-between gap-4">
            <p className="label">Certificate verifier</p>
            <div className="flex gap-2">
              <button onClick={() => certFileRef.current?.click()} className="btn-line !py-2 !px-4 text-[12px]">
                <Upload size={13} />
                Certificate
              </button>
              <button onClick={() => bundleFileRef.current?.click()} className="btn-line !py-2 !px-4 text-[12px]">
                <FileJson size={13} />
                Bundle
              </button>
            </div>
          </div>
          <input ref={certFileRef} type="file" accept="application/json,.json" className="hidden" onChange={(e) => e.target.files?.[0] && readFile(e.target.files[0], "certificate")} />
          <input ref={bundleFileRef} type="file" accept="application/json,.json" className="hidden" onChange={(e) => e.target.files?.[0] && readFile(e.target.files[0], "bundle")} />

          <textarea
            value={certificateText}
            onChange={(event) => setCertificateText(event.target.value)}
            placeholder="Paste the certificate JSON here…"
            spellCheck={false}
            className="mt-5 h-40 w-full resize-y rounded-xl border border-line bg-cream/70 p-4 text-[12.5px] leading-relaxed text-ink placeholder:text-ink-3 focus:border-wax outline-none"
          />
          <textarea
            value={bundleText}
            onChange={(event) => setBundleText(event.target.value)}
            placeholder="Optional: paste the evidence bundle JSON for quote grounding…"
            spellCheck={false}
            className="mt-3 h-24 w-full resize-y rounded-xl border border-line bg-cream/70 p-4 text-[12.5px] leading-relaxed text-ink placeholder:text-ink-3 focus:border-wax outline-none"
          />

          {notice && <p className="mt-3 text-[12.5px] text-ink-3">{notice}</p>}
          {parseError && <p className="mt-3 text-[12.5px] text-wax">Could not parse the input: {parseError}</p>}

          <button
            onClick={() => void run(certificateText, bundleText)}
            disabled={!certificateText.trim() || runState === "running"}
            className="btn-ink mt-5 w-full justify-center disabled:opacity-50 disabled:pointer-events-none"
          >
            {runState === "running" ? <Loader2 size={16} className="animate-spin" /> : <ShieldCheck size={16} />}
            Verify in this browser
          </button>

          {stages && (
            <div className="mt-7">
              <div
                className={`rounded-xl border px-5 py-4 ${
                  passed ? "border-leaf/40 bg-leaf/10" : "border-wax/40 bg-wax/10"
                }`}
              >
                <p className={`text-[13.5px] font-semibold flex items-center gap-2 ${passed ? "text-leaf" : "text-wax"}`}>
                  {passed ? <CheckCircle2 size={16} /> : <XCircle size={16} />}
                  {passed
                    ? `Certificate intact — all ${totalChecks} checks passed.`
                    : `${failedChecks} of ${totalChecks} checks failed. Do not trust this certificate.`}
                </p>
              </div>
              <div className="mt-5 space-y-6">
                {stages.map((stage) => (
                  <div key={stage.title}>
                    <p className="label">{stage.title}</p>
                    <ul className="mt-2.5 space-y-2">
                      {stage.checks.map((check) => (
                        <li key={check.label} className="flex items-start gap-2.5 text-[13px] leading-relaxed">
                          {check.pass ? (
                            <CheckCircle2 size={14} className="text-leaf mt-0.5 shrink-0" />
                          ) : (
                            <XCircle size={14} className="text-wax mt-0.5 shrink-0" />
                          )}
                          <span className={check.pass ? "text-ink-2" : "text-wax font-medium"}>{check.label}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
    </section>
  );
}
